# Array Creation in NumPy

In [1]:
#Exp no.: 5

In [9]:
#Aim : Creating Array using Numpy

In [3]:
#Name: Niraj Satyanarayan Doiphode
#Roll No.:72
#Sec: B
#Subject:ET - 1

In [1]:
import numpy as np

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

[1 2 3 4 5]


In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)

[[1 2 3]
 [4 5 6]]


In [4]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
ones_array = np.ones((2, 4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)

[0 2 4 6 8]


In [7]:
random_array = np.random.rand(3, 3)
print(random_array)

[[0.65727971 0.32006271 0.26366274]
 [0.07218269 0.38383707 0.04568729]
 [0.04902635 0.0682816  0.58838082]]
